import {
  profile,
  user1,
  user2,
  user3,
  user4,
  user5,
  user6,
  user7,
  user8,
  user9,
} from "../../assets/images";

export const userData = [
  {
    id: 1,
    name: "Alice",
    age: 25,
    hobbies: ["Reading", "Painting", "Cooking"],
    bio: "Hello! I'm Alice, an avid reader who loves to paint and cook. Let's explore the world of literature, create art, and savor delicious meals together.",
    distance: "3 miles away",
    imgUrl: user1,
    gender: "female",
  },
  {
    id: 2,
    name: "Bob",
    age: 32,
    hobbies: ["Hiking", "Photography", "Gaming"],
    bio: "Greetings! I'm Bob, a nature enthusiast who enjoys capturing moments through photography and gaming adventures. Let's embark on a hike and create our own epic stories.",
    distance: "10 miles away",
    imgUrl: user2,
    gender: "male",
  },
  {
    id: 3,
    name: "Eva",
    age: 27,
    hobbies: ["Dancing", "Traveling", "Yoga"],
    bio: "Hola! I'm Eva, a dance lover who finds joy in exploring new cultures and practicing yoga. Let's dance, travel the world, and find serenity together.",
    distance: "2 miles away",
    imgUrl: user3,
    gender: "female",
  },
  {
    id: 4,
    name: "David",
    age: 28,
    hobbies: ["Soccer", "Cooking", "Movies"],
    bio: "Hi there! I'm David, a soccer enthusiast who enjoys culinary adventures and movie nights. Let's kick a ball, cook up a storm, and enjoy cinematic wonders together.",
    distance: "5 miles away",
    imgUrl: user4,
    gender: "male",
  },
  {
    id: 5,
    name: "Grace",
    age: 26,
    hobbies: ["Drawing", "Reading", "Hiking"],
    bio: "Hey! I'm Grace, an artist who finds inspiration in drawing and immersing myself in captivating stories. Let's explore the beauty of art and nature together.",
    distance: "7 miles away",
    imgUrl: user5,
    gender: "female",
  },
  {
    id: 6,
    name: "Sophie",
    age: 29,
    hobbies: ["Singing", "Writing", "Sailing"],
    bio: "Ciao! I'm Sophie, a melody-maker who finds solace in writing and the serenity of sailing. Let's harmonize our voices and create music together. A poetic soul searching for someone to sail through life's highs and lows.",
    distance: "4 miles away",
    imgUrl: user6,
    gender: "female",
  },
  {
    id: 7,
    name: "Chris",
    age: 30,
    hobbies: ["Guitar", "Surfing", "Photography"],
    bio: "Hello! I'm Chris, a guitar enthusiast who loves riding the waves and capturing moments through photography. Let's make music, surf, and create lasting memories together.",
    distance: "4 miles away",
    imgUrl: user7,
    gender: "male",
  },
  {
    id: 8,
    name: "Michael",
    age: 31,
    hobbies: ["Surfing", "Gardening", "Cooking"],
    bio: "Hi there! I'm Michael, a surfer who finds joy in the garden and the magic of cooking. Let's ride the waves, tend to the garden, and enjoy delicious meals together.",
    distance: "8 miles away",
    imgUrl: user8,
    gender: "male",
  },
  {
    id: 9,
    name: "Daniel",
    age: 28,
    hobbies: ["Yoga", "Hiking", "Photography"],
    bio: "Hello, I'm Daniel, a yoga enthusiast who finds peace in the serenity of nature and expression through photography. Let's go on a hike and then strike a pose together. Looking for someone to share adventures and good food with.",
    distance: "9 miles away",
    imgUrl: user9,
    gender: "male",
  },
];


export const chatData = [
  {
    id: 1,
    name: "Alice",
    imgUrl: user1,
    age: 25,
    isOnline: true,
    lastMessage:
      "That sounds like a lot of fun. Would you like to go together sometime?",
    date: "2023-10-15",
    timeSent: "5 mins",
    chat: [
      {
        sender: "me",
        message: "Hi there! How's it going?",
        timestamp: "10:00 AM",
      },
      {
        sender: "Alice",
        message: "I am doing great, thanks!",
        timestamp: "10:05 AM",
      },
      {
        sender: "me",
        message: "Have any exciting plans for the weekend? 😊",
        timestamp: "10:10 AM",
      },
      {
        sender: "Alice",
        message: "Yes, I'm thinking of going hiking. 🏞️ What about you?",
        timestamp: "10:15 AM",
      },
      {
        sender: "me",
        message: "That sounds amazing! I might just tag along. 🥾",
        timestamp: "10:20 AM",
      },
      {
        sender: "Alice",
        message: "That would be great! The more, the merrier. 🌟",
        timestamp: "10:25 AM",
      },
    ],
  },

  {
    id: 2,
    name: "Daisy",
    imgUrl: user2,
    age: 30,
    isOnline: false,
    lastMessage: "Absolutely! Let's make it happen. When are you free?",
    date: "2023-10-14",
    timeSent: "10 mins",
    chat: [
      {
        sender: "me",
        message: "Hey Daisy, how have you been?",
        timestamp: "11:00 AM",
      },
      {
        sender: "Daisy",
        message: "I've been good. How about you?",
        timestamp: "11:05 AM",
      },
      {
        sender: "me",
        message: "I've been a bit busy, but managing. 😊",
        timestamp: "11:10 AM",
      },
      {
        sender: "Daisy",
        message: "I understand. We should catch up soon! ☕",
        timestamp: "11:15 AM",
      },
      {
        sender: "me",
        message: "Definitely! Let's plan something for this weekend. 🎉",
        timestamp: "11:20 AM",
      },
      {
        sender: "Daisy",
        message: "Sure, that sounds good. When are you free? 🗓️",
        timestamp: "11:25 AM",
      },
      {
        sender: "me",
        message: "I'm free on Saturday afternoon. How about you? 🌤️",
        timestamp: "11:30 AM",
      },
      {
        sender: "Daisy",
        message: "Saturday works for me too! Let's meet at our usual spot. 🍔",
        timestamp: "11:35 AM",
      },
      {
        sender: "me",
        message: "Sounds like a plan! See you then. 👋",
        timestamp: "11:40 AM",
      },
    ],
  },

  {
    id: 3,
    name: "Olivia",
    imgUrl: user3,
    age: 28,
    isOnline: true,
    lastMessage: "Sounds like a plan! Let's make it happen.",
    date: "2023-10-11",
    timeSent: "25 mins",
    chat: [
      {
        sender: "me",
        message: "Hi Olivia, how's your day going?",
        timestamp: "2:00 PM",
      },
      {
        sender: "Olivia",
        message: "It's going great! Enjoying the sunshine. How about you?",
        timestamp: "2:05 PM",
      },
      {
        sender: "me",
        message: "That's wonderful! I'm just getting through some work. 💻",
        timestamp: "2:10 PM",
      },
      {
        sender: "Olivia",
        message: "Don't work too hard! Make sure to take breaks. 🌞",
        timestamp: "2:15 PM",
      },
      {
        sender: "me",
        message:
          "Absolutely, breaks are necessary. Planning anything fun for the evening? 🎉",
        timestamp: "2:20 PM",
      },
      {
        sender: "Olivia",
        message: "I might go to the gym later. Need to work off some steam. 💪",
        timestamp: "2:25 PM",
      },
      {
        sender: "me",
        message: "That's a great idea! I should join you sometime. 🏋️‍♂️",
        timestamp: "2:30 PM",
      },
      {
        sender: "Olivia",
        message: "Definitely! The more, the merrier. 🤸‍♂️",
        timestamp: "2:35 PM",
      },
    ],
  },

  {
    id: 4,
    name: "Betty",
    imgUrl: user4,
    age: 32,
    isOnline: true,
    lastMessage: "Hi there! How's it going?",
    date: "2023-10-15",
    timeSent: "5 mins",
    chat: [
      {
        sender: "me",
        message: "Hi there! How's it going?",
        timestamp: "10:00 AM",
      },
      {
        sender: "Betty",
        message: "I am doing great, thanks!",
        timestamp: "10:05 AM",
      },
      {
        sender: "me",
        message: "Have any exciting plans for the weekend? 😊",
        timestamp: "10:10 AM",
      },
      {
        sender: "Betty",
        message: "Yes, I'm thinking of going hiking. 🏞️ What about you?",
        timestamp: "10:15 AM",
      },
      {
        sender: "me",
        message: "That sounds amazing! I might just tag along. 🥾",
        timestamp: "10:20 AM",
      },
      {
        sender: "Betty",
        message: "That would be great! The more, the merrier. 🌟",
        timestamp: "10:25 AM",
      },
    ],
  },

  {
    id: 5,
    name: "Lily",
    imgUrl: user5,
    age: 29,
    isOnline: false,
    lastMessage: "Hi there! How's everything going?",
    date: "2023-10-09",
    timeSent: "35 mins",
    chat: [
      {
        sender: "me",
        message: "Hi Lily, how's everything going?",
        timestamp: "4:00 PM",
      },
      {
        sender: "Lily",
        message: "Things are going well. How about you?",
        timestamp: "4:05 PM",
      },
    ],
  },

  {
    id: 6,
    name: "Chiara",
    imgUrl: user6,
    age: 28,
    isOnline: true,
    lastMessage: "Sounds like a great idea. Let's make it happen.",
    date: "2023-10-07",
    timeSent: "45 mins",
    chat: [
      {
        sender: "me",
        message: "Hey Chiara, how's your week been?",
        timestamp: "6:00 PM",
      },
      {
        sender: "Chiara",
        message: "It's been busy but good. How about you?",
        timestamp: "6:05 PM",
      },
    ],
  },

];

export const datesData = [
  {
    id: 1,
    imgUrl: user1,
    name: "Alice",
    lastName: "Johnson",
    age: 25,
    city: "New York",
    country: "USA",
  },
  {
    id: 2,
    imgUrl: user2,
    name: "Bob",
    lastName: "Smith",
    age: 32,
    city: "Los Angeles",
    country: "USA",
  },
  {
    id: 3,
    imgUrl: user3,
    name: "Eva",
    lastName: "Jones",
    age: 27,
    city: "London",
    country: "UK",
  },
  {
    id: 4,
    imgUrl: user4,
    name: "David",
    lastName: "Williams",
    age: 28,
    city: "Sydney",
    country: "Australia",
  },
  {
    id: 5,
    imgUrl: user5,
    name: "Grace",
    lastName: "Brown",
    age: 26,
    city: "Paris",
    country: "France",
  },
  {
    id: 6,
    imgUrl: user6,
    name: "Sophie",
    lastName: "Miller",
    age: 29,
    city: "Berlin",
    country: "Germany",
  },
  {
    id: 7,
    imgUrl: user7,
    name: "Chris",
    lastName: "Wilson",
    age: 30,
    city: "Toronto",
    country: "Canada",
  },
  {
    id: 8,
    imgUrl: user8,
    name: "Michael",
    lastName: "Moore",
    age: 31,
    city: "Tokyo",
    country: "Japan",
  },
  {
    id: 9,
    imgUrl: user9,
    name: "Daniel",
    lastName: "Taylor",
    age: 28,
    city: "Mumbai",
    country: "India",
  },
  {
    id: 10,
    imgUrl: user4,
    name: "Grace",
    lastName: "Anderson",
    age: 30,
    city: "Moscow",
    country: "Russia",
  },
];


export const profileData = [
  {
    name: "Alice Johnson",
    age: 25,
    imgUrl: user1,
    hobbies: ["Reading", "Painting", "Cooking"],
    bio: "Hello! I'm Alice, an avid reader who loves to paint and cook. Let's explore the world of literature, create art, and savor delicious meals together.",
  },
];